# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-20.04
    container: openjdk:15.0
    
    steps:
    - uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
      
  check:

    runs-on: ubuntu-20.04
    needs: build
    
    steps:
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 15
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew sonarqube -Dsonar.host.url=https://sonarcloud.io -Dsonar.scm.provider=git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      
      
  
